name: Manual Action Workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level (warning, urgent, testing or others)'
        required: true
      flutterVersion:
        description: 'Input Flutter version, please input 2.2.3'
        required: true
        default: '2.2.3'

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '${{ github.event.inputs.flutterVersion }}'
      - run: flutter pub get
      - run: flutter build apk
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Flutter Versio: ${{ github.event.inputs.flutterVersion }}"
      - uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/apk/release/app-release.apk
