name: Manual Action Workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
      description:
        description: 'Description'
        required: true

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter pub get
      - run: flutter build apk
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.description }}"
      - uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/apk/release/app-release.apk
